
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-migrate-job"
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-2"
    "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
  template:
    spec:
      automountServiceAccountToken: false
      containers:
        - name: db-migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
              ephemeral-storage: "2Gi"
          
          command: 
            - python
            - manage.py
            - migrate
            - --noinput
            - -v
            - "2"
          
          envFrom:
            - secretRef:
                name: db-credentials
      
      restartPolicy: OnFailure
  backoffLimit: 3
